### ISSUE TITLE
关于shadowsocks客户端实现

### ISSUE THREAD

**Issue by ewangteng** [380wmda999/client#1]
可否帮我科普一下shadowsocks客户端实现步骤呢？我准备用java实现一个公用的工具，以方便我把sslocal功能与现有web项目进行整合。

**Comment by 380wmda999** [comment]
实现 shadowsocket的客户端连接协议就行了

**Comment by ewangteng** [comment]
好的，

**Comment by wangri818** [comment]
你好 请问实现sslocal和web项目整合的功能了吗
